### ISSUE TITLE
0.0.3 release is not in index.yaml

### ISSUE THREAD

**Issue by TJM** [cormachogan/vsphere-csi-helmchart#1]
Not sure exactly how it all works together, but the index.yaml does not have the 0.0.3 release.... however 0.0.2 points to the 0.0.3 tgz, so its effectively the same, right? Just thought I'd let you know there was some funkiness there.

**Comment by cormachogan** [comment]
Thanks for the heads up.

**Comment by mylesagray** [comment]
Fixed in commit ef3e4a71fb2cad64d5536a71e9b150b8bc53decf
