### ISSUE TITLE
Reset gh-pages branch

### ISSUE THREAD

**Issue by TJM** [cormachogan/vsphere-csi-helmchart#11]
I tried to do a PR for this, but it won't let me

I would suggest resetting your gh-pages branch completely...

```bash
git checkout master
git branch -D gh-pages # remove local branch
git checkout --orphan gh-pages
git rm -rf charts README.md
git commit -m 'Reset gh-pages'
git push -f origin gh-pages
```

This, of course assumes your github remote is named `origin` :)

That way there is not an out-of-date copy of everything in gh-pages...

**Comment by mylesagray** [comment]
@TJM - Why are we removing `charts/` and `README.md` as this is the public facing version of the docs - the `charts/` dir in particular is hosted there to allow it to be added as a helm repo - unless I'm misunderstanding something?

**Comment by TJM** [comment]
OK, you have a point, I was actually looking for a way to automate the deployment of the index.yaml, and came across a blog post that suggested those steps. I guess you could also automate updates to the README.md too?

On a related note.... The README.md is blank in the chart directory. Perhaps it would be better to migrate the current readme into that and focus the top level readme on adding the repository and (somehow) generate a list of the charts contained within? (shrug)

I was honestly more focused on preventing an outdated copy of the chart from showing up in the gh-pages branch. Perhaps it would be better to just configure gh-pages to use `master` and dump the gh-pages branch? (shrug)

As to the helm repo part... the index.yaml is the magic sauce that allows it to be used as a helm repo, and per that file:
```
    urls:
    - https://github.com/cormachogan/vsphere-csi-helmchart/releases/download/0.0.3/vsphere-csi-0.0.3.tgz
    version: 0.0.3
```
It is using the "github" tag/release feature to make the downloadable helm charts available, so the charts dir is technically not needed, but we do need to get some github actions setup.

I have been referencing: https://jamiemagee.co.uk/blog/how-to-host-your-helm-chart-repository-on-github/

EDIT 3?: For what its worth, I am still not sure why the "root" of the repo is not charts/vsphere-csi, It sure seems like it would simplify a lot... given its a public repo and we do not have to pay a per-repo cost. ;) I am not sure why you would want to have multiple charts in a single repo. Of course, for an "organization" who would want to publish multiple charts into the same "repo" they would probably want to have a central repo where the index.yaml could be located that would combine all the different repos, and maybe that is difficult :-/

**Comment by mylesagray** [comment]
Closing as repo in new location - feel free to reopen there: https://github.com/vsphere-tmm/helm-charts
