### ISSUE TITLE
values.yaml has duplicate keys

### ISSUE THREAD

**Issue by benhwebster** [cormachogan/vsphere-csi-helmchart#12]
https://github.com/cormachogan/vsphere-csi-helmchart/blob/ed3da60c5e4bdc087c6caa3061e9b1cb2a027a9f/charts/vsphere-csi/values.yaml#L162-L173
Also not sure which pods/deployments these settings apply to, is it for all pods created by the chart?

**Comment by cormachogan** [comment]
Resolved
