### ISSUE TITLE
Release new Version with additional values.yaml

### ISSUE THREAD

**Issue by asta1992** [cormachogan/vsphere-csi-helmchart#13]
Is it possible to release the new version of the chart with the new additional values like "csiController"?

**Comment by cormachogan** [comment]
The VMware CSI engineering team have decided to develop an Operator to deploy and manage CSI, rather than go with a helm chart approach. Thus, it is unlikely that we will see much more work done on the helm chart unless the community decide to support it, which would be very welcome.

**Comment by mylesagray** [comment]
Closing as repo in new location - feel free to reopen there: https://github.com/vsphere-tmm/helm-charts
