### ISSUE TITLE
namespace is not set correctly (hard coded to kube-system) on several resources

### ISSUE THREAD

**Issue by TJM** [cormachogan/vsphere-csi-helmchart#2]
We try to keep kube-system from being filled up with a bunch of third party resources, so I was using

--set config.namespace=vsphere

... but stuff didnt start up because some things (secret) were created in the specified namespace, while others (deployment/vsphere-csi-controller; daemonset/vsphere-csi-node; serviceAccount/vsphere-csi-controller)

Specifically, the csi-controller couldn't start cause it couldn't find the secret.

**Comment by cormachogan** [comment]
The helm chart was written to reproduce the manual install steps outlined in the vSphere CSI documentation. It places everything into kube-system. I will need to check that it is acceptable to deploy the vSphere CSI in another namespace.

**Comment by TJM** [comment]
I thought it might be converted from manual steps. It might be worth starting from a new helm chart to get some of the normal stuff that is covered with values. I will have to look and see, but I don't think that "namespace" is normally specified at all inside of charts, usually that is either the current namespace when the chart is installed or (--namespace whatever) during helm install. Let me know ;)

**Comment by cormachogan** [comment]
This should be good for the CSI driver - spoke to the dev who said that we have not hardcoded the `kube-system` anywhere is the CSI driver so it should be fine. However I don't yet know about the CPI/CCM which we included in a linked chart. Still checking on that.
