### ISSUE TITLE
Why is the controller running on a master? (and CPI?)

### ISSUE THREAD

**Issue by TJM** [cormachogan/vsphere-csi-helmchart#9]
After diving into the templates in other issues, it occurs to me that the controller pod is being configured to run on a master, and IMO it should not be. Do we know why this is the case?

For a point of comparison, Pure Storage CSI does not: https://hub.helm.sh/charts/purestorage/pure-csi

Also there is this "CPI" pod that is *also* running on the masters (all of them, as a daemonset).

**Comment by cormachogan** [comment]
This is per the vSphere CSI driver development team. The helm chart is simply following their design choices. If you feel this is not correct, this would need to be addressed to them via vSphere CSI issues.
